# Flake8 test the repo.

name: Flake8

on:
  push:
    branches: [ main, WD, manke]
  pull_request:
    branches: [ main, WD, manke]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: flake8
        uses: actions/checkout@v2
        with:
          python-version: 3.9.2
      - run: |
          $CONDA/bin/conda env create --file env.yml
          $CONDA/bin/conda activate dissectBCL 
          pip install ./
          flake8  
