# pytests

name: pytest

on:
  push:
    branches: [ main, WD, manke ]
  pull_request:
    branches: [ main, WD, manke ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: bioconda, conda-forge, defaults
          use-only-tar-bz2: true 
          auto-update-conda: true
          auto-activate-base: true
      - name: pytest
        run: |
          conda env create --file env.yml
          conda activate dissectBCL 
          pip install ./  
          coverage run -m pytest
          coverage report -m  
