# pytests

name: pytest

on:
  push:
    branches: [ main, WD ]
  pull_request:
    branches: [ main, WD ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pytest
        uses: actions/checkout@v2
        with:
          python-version: 3.10.1
      - run: |
          python -m pip install --upgrade pip  
          pip install ./  
          coverage run -m pytest tests/test.py  
          coverage report -m  
